### ISSUE TITLE
#include "samplerate.h" necessary?

### ISSUE THREAD

**Issue by jack126guy** [bipscript/bipscript#1]
I see this include in `btrack/BTrack.cpp`. I assume it refers to libsamplerate, but it's not listed as a dependency on bipscript.org and I can't find any uses of the libsamplerate API. I removed it and everything still seems to work.

**Comment by jhammen** [comment]
You are correct - the local Btrack is modified and does not need libsamplerate so it is safe to remove. It has now been removed from the code in git. Thanks for the report!
