### ISSUE TITLE
Wonder if there is way to use carla in scripts

### ISSUE THREAD

**Issue by Cloudef** [bipscript/bipscript#4]
This is more of a question than issue.

I'm thinking of giving bipscript as test run for compositing and mixing. I need carla for few properiatery sample players. I'm not deeply familiar with lv2, and could not find way to interact with carla-patchbay in such detail that I'm able to load in a VST plugin for example and set its parameters. (Loading saved carla session would be fine too). Workaround would be to use carla standalone and connect apporiate jack ports, but would love if this would not be needed so the script can essentially be "self-containing" (like a recipe for a piece).

There is api reference for lv2 plugin state which can be given in constructor when loading plugin, but not really sure how I could get this state for example from pre-made carla-patchbay session.

**Comment by jhammen** [comment]
This is an excellent question. Right now Carla works in a local development branch via state file loading. I will clean up and commit ASAP, more information soon.

**Comment by Cloudef** [comment]
Very exciting. I'll look forward to that.

**Comment by jhammen** [comment]
I was able to get it to work, not sure the best way to create LV2 patches in Carla but this worked for me:

* Launch carla using jalv: `$ jalv.gtk http://kxstudio.sf.net/carla/plugins/carlapatchbay`

* Create the patch in the patchbay, I was able to use VST plugins.

* Export the patch using the "save preset" menu option (on jalv, not carla) - this creates a folder with a manfest and a main ttl file - the latter is all you need.

Now instaniating Carla LV2 in bipscript looks like

`local carla = Lv2.Plugin(IO.File("./test.ttl"))`

Now it is a normal Lv2.Plugin object, you can change control settings, connect to inputs/outputs, schedule notes etc.

**Comment by Cloudef** [comment]
Thanks, I'll try it.

**Comment by Cloudef** [comment]
Works well :+1:

**Comment by Cloudef** [comment]
Now if it just was possible to reload scripts without reloading lv2 plugs it would be perfect. But that may be out of scope of bipscript.

**Comment by jhammen** [comment]
Plugins are cached for future runs of the script, they should not reload as long as the script process is still running. The script itself will reload if you rewind the transport, currently there is no way to manually trigger a script reload.

If you have a DAW that can act as Jack transport master you can make changes while the script is playing, rewind a bit and you will hear the changes. Set loop points in the DAW and it will pick up changes in the script every time the loop restarts.

There should probably be a tutorial lesson about this..

**Comment by Cloudef** [comment]
>The script itself will reload if you rewind the transport, currently there is no way to manually trigger a script reload.

Ah I was not aware of this.
I'm aware of how jack transport works, so this should be all good for me now. 
Thank you for your great work.
