### ISSUE TITLE
[QUESTION] Midi channel from usb controler

### ISSUE THREAD

**Issue by bda65** [bipscript/bipscript#6]
Hi,
I've tried to add channel 1 to the controlplugins example. I can't filter channel input from the usb controller.
Do i need to add midifilter (from x42-plugins) for channel filtering?
Actually, if i send CC 19 to channel 1 and 2, my synth respond to all almost if i add synth.midiChannel(1).

**Comment by jhammen** [comment]
Hello, it is true, at this moment there is no filter by CC channel

I agree it's a nice feature to have in the API for a future version, for now the best solution is yes probably the midifilter plugin

the midiChannel method lacks documentation - it only sets the default channel for scheduling on the plugin i.e.

```
plugin.schedule(note, 1.0) // play on channel 1
plugin.midiControl(2)
plugin.schedule(note, 1.0) // play on channel 2
plugin.schedule(note, 1.0, 3) // play on channel 3
```

**Comment by bda65** [comment]
Thanks.
I'll use midifilter for now.
bipscript is great. I like it :)

**Comment by jhammen** [comment]
hey glad you like it!

you have uncovered a real issue: control mapping MIDI -> LV2 needs a CC *and* channel number, next revision of the API should handle this

but it's a simple change to filter by the default channel so I have done that [e566fa79591d9db72fb9f87e027cd16cc4456b4d]

now it will filter on the plugin's default midi channel (which is '1' until set otherwise):

synth.addController(controller, 7, "volume") // CC 7 on channel 1 -> lv2 "volume" port
synth.midiChannel(2) // default midi channel changed
synth.addController(controller2, 10, "pan") // CC 10 on channel 2 -> lv2 "pan" port

this is ready now if you can build from source

**Comment by bda65** [comment]
Awesome :)
I'll try it soon.
Actually, i'm wrinting an article / tuto for bipscript on the french linux musician community: http://linuxmao.org/Bipscript
Bipscript is the tool i'm searching for a long time. I'm using it for controlling LV2 plugins running on a Raspberry Pi 4b without screen with a hardware sequencer.
Now I need to remove midifilter plugin instance in my script ;)
Thanks very much.

**Comment by jhammen** [comment]
definitely want to support the raspberry pi but never had time to try it myself so that's fantastic

thank you for writing the article, LinuxMAO looks like a great site, je viens de m'inscrire :)

**Comment by bda65** [comment]
Your patch work well on lv2 plugins that handle midi_input and midi_channel ports. Many plugins doesn't have those ports and need midifilter plugin as before.
I don't know why many lv2 plugins do not have midi ports...
Raspberry Pi are great for many things.  The 4b has the power of a little x86 PC.
My actuel music setup has one. For synths and effects. Controlled with an arduino based midi controller and my Gotharman's Little deFormer 3 workstation/groovebox.
Thanks for this little but important patch :)

**Comment by jhammen** [comment]
that sounds like a great studio setup!

things should work even for plugins without midi input, I can do this with the controlplugins example:

```
reverb.midiChannel(5)
reverb.addController(controller, 7, "amount", 0, 1)
```
but it seems wrong - why would a purely audio plugin have a default midi channel? it should not

I have to say, it all these difficulties are pointing to the poor design of the addControllers method, it is from long ago, before the callbacks existed, they are the better solution, something like:

```
midiInput.onControl(function(cc, m) {
  if(cc.channel == 1 && cc.controller == 5) {
    synth.control("lfo", cc.value / 8)
  }
})
```

it's more code, but of course can be wrapped in a bipscript method or class for the same level of convenience, also far more flexible, each user has different needs

but I don't think the above code works right now - need to fix that and update the controlplugins example..

**Comment by bda65** [comment]
Sorry for this. That's was a bug in my script! Now it work well.
Nekobi from distrho has no midi port but work well.
Now i need to filter the midi note on/off per channel but that's seem easy.
Tanks for your help.

**Comment by jhammen** [comment]
Closing as solved for now, thanks for reporting.

Thank you also for creating that wiki article on linuxMAO, very useful!
